name: CI pipeline
on:
  push:
    branches:
      - main
      - 'ci_*'

env:
  VERSION: '1.0.0'

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
        run:
            working-directory: Week-08-CICD/backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{vars.GH_PYTHON_VERSION}}
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('Week-08-CICD/backend/requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-
    
    - name: Install dependencies
      env:
        MLFLOW_VERSION: '2.19.0'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow==${{env.MLFLOW_VERSION}}
