name: CI Docker Builder

on:
    workflow_run:
        workflows: [CI pipeline]
        types:
            - completed
        branches:
            - main
            - "ci_*"

    workflow_dispatch:

jobs:
    build-and-push:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: Week-08-CICD/backend
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.GH_DOCKERHUB_USERNAME }}
            password: ${{ secrets.GH_DOCKERHUB_TOKEN }}
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Build and Push
          uses: docker/build-push-action@v6
          with:
            context: Week-08-CICD/backend
            file: Week-08-CICD/backend/Dockerfile
            push: true
            tags: ${{ vars.GH_BACKEND_IMAGE }}
