name: CI Docker Builder

on:
    push:
        branchs:
            - main
            - 'ci_*'

jobs:
    build-and-push:
        needs: test
        if: github.event_name == 'push'
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: Week-08-CICD/backend
        steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{vars.GH_DOCKERHUB_USERNAME}}
            password: ${{secrets.GH_DOCKERHUB_TOKEN}}
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            name: ${{vars.GH_BACKEND_IMAGE}}
        
        - name: Build and Push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{vars.GH_BACKEND_IMAGE}}
